// Generated by scripts/write-screen-share-rollout.mjs before Electron compile.
// Tracked default stays fail-closed for development, PR, and release builds.
export const NATIVE_SCREEN_AUDIO_ENABLED = false as boolean;
